import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import { Open_Sans } from "next/font/google";

import "./globals.css";
import Provider from "./provider";
import { Toaster } from "sonner";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  // You can add more options like:
  // weight: ['400', '700'], // Specific weights you need
  // style: ['normal', 'italic'],
});
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${openSans.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <body
        className={openSans.className}
      >
        <Provider>
          {children}
          <Toaster/>
        </Provider>
      </body>
    </html>
  );
}
